### ISSUE TITLE
PDW fragmented messages

### ISSUE THREAD

**Issue by Shaggs** [micolous/cfsprinter#16]
As your aware PDW sometimes has "fragmented"  messages this is caused when the bitrate is not 1600.

with fragmented messages the bitrate changes from 1600 to 1601. On average there is an 8 seccond delay between fragmented messages 1600 and the 1601. If broken into more the 1601 changes to 1602 etc

A dirty fix is to add bitrate to the to pdw output and add an ` if `condition and store the flexcode to marry it all up.
   flexcode, mtime, mdate, bitrate, msg = message.split(' ', 4)

		when = datetime.strptime(mdate + 'T' + mtime, '%d-%m-%yT%H:%M:%S')
		flexcode = int(flexcode)
		msg = msg.strip()
                bitrate = str(bitrate)
then add somesort of `if bitrate is not "1600"` store the capcode sleep for 8 secconds and join the msg with the same capcode.

a sceen shot of a fragmented message and bitrate difference.
![bitrate](https://cloud.githubusercontent.com/assets/769737/18605311/a12e9004-7ccd-11e6-9023-97a8418e5776.jpg)

This idea is better than the alternative that is scraping the logfile for fragmented messages and putting it all back together

**Comment by micolous** [comment]
It looks like the second message has the non-standard bitrate (1601), so it would mean delaying *every* incoming pager message to handle the possibility that it is fragmented.

Really, I'd want it the other way around, so that a fragmented message has the first part at a higher rate than the continuations.

I think this is a bug in PDW.

What would be interesting to compare is flex-decoders running on rtl_sdr, if they expose the fragmentation any better.  But a cursory look into this seems to indicate that most people are using this with PDW, which doesn't really help much.

**Comment by Shaggs** [comment]
So after some testing multimon-ng doent support the 1601 bitrate so it only prints the 1600 bitrate so issue started with multimon-ng so back to the drawing board..

**Comment by Shaggs** [comment]
Overnight I tired link above but unfortunately the youtube video linked no longer works.

What I could do is run multimon and record the FLEX sounds and put it on dropbox and you could make a loop in your audio (headphone output to microphone input using double male cable) 

Doing it this way you will have a FLEX input to work with (I've done this previously works well ). I can also upload the log from pdw and mulitimon to play spot the difference.

Let me know

**Comment by Shaggs** [comment]
After some extenive testing multimon does not support 1601 bitrate. In the pdw source code ive found where the magic happens but I cant port it accross to multimon-ng as i have no idea about C.

What would like to try is the gold every pager message for 3 secconds not 8 and lets see what happens. This how the web feeds handle it.
